---
dist: xenial
language: python

before_install:
 - ln -s ansible-wef ../juju4.wef
install:
  - sudo apt-get install libxml2-utils
  - pip install ansible ansible-lint
  - ansible --version
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
  - "echo \"localhost\" > inventory"
  - ansible-galaxy install -p .. -r requirements.yml

script:
  - "ansible-lint tasks/main.yml || true"

# Check the role/playbook's syntax.
  - "ansible-playbook -i inventory --syntax-check test/integration/default/default.yml"
