---

- name: Appveyor environment variables
  include_vars: appveyor.yml
  when: >
    (ansible_env is defined and ansible_env.APPVEYOR is defined and ansible_env.APPVEYOR) or
    ansible_user == 'winrm_test_user'
- name: Vagrant environment variables
  include_vars: vagrant.yml
  when: ansible_user == 'vagrant'

- name: variable check
  fail:
    msg: "Please define wef_user/wef_pass variables."
  when: wef_user is not defined and _wef_user is not defined

- name: Windows | WEF
  include: wef.yml
  when: ansible_os_family == "Windows"

- name: Testing
  include: testing.yml
  when: ansible_os_family == "Windows" and wef_testing|bool
