---
# https://github.com/clong/DetectionLab/blob/master/Vagrant/scripts/install-microsoft-ata.ps1

- name: Microsoft ATA Lightweight gateway | Download
  win_get_url:
    url: https://wef/api/management/softwareUpdates/gateways/deploymentPackage
    dest: 'c:\tmp\gatewaysetup.zip'
    validate_certs: false
    url_username: wef\vagrant
    url_password: vagrant
  delegate_to: "{{ wef_atalight_target | default('dc') }}"

- name: Microsoft ATA Lightweight gateway | Unzip
  win_unzip:
    src: c:\tmp\gatewaysetup.zip
    dest: C:\tmp\gatewaysetup
    creates: c:\tmp\gatewaysetup\Microsoft ATA Gateway Setup.exe
  delegate_to: "{{ wef_atalight_target | default('dc') }}"

- name: Microsoft ATA Lightweight gateway | Check for presence
  win_stat:
    path: 'C:\Program Files\Microsoft Advanced Threat Analytics'
  register: ata
  delegate_to: "{{ wef_atalight_target | default('dc') }}"

- name: Microsoft ATA Lightweight gateway | Run installer
  win_package:
    path: 'C:\tmp\gatewaysetup\Microsoft ATA Gateway Setup.exe'
    arguments: /q NetFrameworkCommandLineArguments=`"/q`" ConsoleAccountName=`"wef\vagrant`" ConsoleAccountPassword=`"vagrant`"
    #product_id: 35a4e767-0161-46b0-979f-e61f282fee21
    state: present
  delegate_to: "{{ wef_atalight_target | default('dc') }}"

- name: Sleeping 5 minutes to allow ATA gateway to start up...
  pause:
    seconds: 300
  delegate_to: "{{ wef_atalight_target | default('dc') }}"

- name: Microsoft ATA Lightweight gateway | Ensure service started
  win_service:
    name: ATAGateway
    state: started
    start_mode: auto
  delegate_to: "{{ wef_atalight_target | default('dc') }}"

- name: Get ATA config
  win_uri:
    url: https://localhost/api/management/systemProfiles/gateways
    validate_certs: false
  register: config
  changed_when: false
  delegate_to: "{{ wef_atalight_target | default('dc') }}"

- debug: var=config

# $config[0].Configuration.DirectoryServicesResolverConfiguration.UpdateDirectoryEntityChangesConfiguration.IsEnabled = $true
- name: Set dc as domain synchronizer
  win_uri:
    url: https://localhost/api/management/systemProfiles/center/$($config[0].Id)
    method: POST
    content_type: "application/json"
    body: ($config[0] | convertto-json -depth 99)
    validate_certs: false
  delegate_to: "{{ wef_atalight_target | default('dc') }}"
