---

- name: Set timezone to UTC
  win_timezone:
    timezone: UTC

- name: Ping DetectionLab server for usage statistics
  win_uri:
    url: "https://detectionlab.network/{{ ansible_hostname }}-Ansible"
    method: GET
    http_agent: "DetectionLab-{{ ansible_hostname }}-Ansible"
  ignore_errors: true
  when: detectionlab_stats|bool

- name: Disable IPv6 all interfaces
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
    name: DisabledComponents
    data: 255
    type: dword
  notify:
    - Disable IPv6 on all network adapters

- name: Copy DetectionLab background image
  win_copy:
    src: "{{ detectionlab_gitroot }}\\vagrant\\resources\\windows\\background.bmp"
    dest: c:\Program Files\sysinternals\background.bmp
    remote_src: true

- name: Copy DetectionLab bginfo config
  win_copy:
    src: "{{ detectionlab_gitroot }}\\vagrant\\scripts\\bginfo.bgi"
    dest: c:\Program Files\sysinternals\bginfo.bgi
    remote_src: true

- name: Check current wallpaper if Bginfo
  win_reg_stat:
    path: HKCU:\Control Panel\Desktop\WallPaper
  register: wallpaper

- debug: var=wallpaper

# FIXME! executing fine but no change of background. ok if manual
- name: Enable DetectionLab bginfo
  win_command: >
    "c:\\ProgramData\\chocolatey\\bin\\bginfo.exe" /accepteula "c:\\Program Files\\sysinternals\\bginfo.bgi" /silent /timer:0
  when: wallpaper.value is defined and not ("BGInfo.bmp" in wallpaper.value)

- name: Set background to be "fitted" instead of "tiled"
  win_regedit:
    key: HKCU:\Control Panel\Desktop
    value: "{{ item.v }}"
    data: "{{ item.d }}"
    datatype: string
  with_items:
    - { v: TileWallpaper, d: '0' }
    - { v: WallpaperStyle, d: '6' }
  notify:
    - Set Task Manager prefs
