---
# https://github.com/clong/DetectionLab/blob/master/Vagrant/scripts/install-windows_ta.ps1

- name: Installing the Windows TA for Splunk
  win_command: >
    "C:\\Program Files\\SplunkUniversalForwarder\\bin\\splunk.exe" install app "{{ detectionlab_splunk_app }}" -auth "admin:{{ wef_splunk_passwd | default('changeme') }}"
  args:
    creates: 'C:\Program Files\SplunkUniversalForwarder\etc\apps\Splunk_TA_windows\default'
  when: detectionlab_online|bool
  ignore_errors: true
  register: winta

- block:
    - name: Update the Windows TA for Splunk
      win_command: >
        "C:\\Program Files\\SplunkUniversalForwarder\\bin\\splunk.exe" install app -update "{{ detectionlab_splunk_app }}" -auth "admin:{{ wef_splunk_passwd | default('changeme') }}"
      args:
        creates: 'C:\Program Files\SplunkUniversalForwarder\etc\apps\Splunk_TA_windows\default'
      # FIXME! Cannot perform action "POST" without a target name to act on
      ignore_errors: true
  when:
    winta is failed and
    detectionlab_online|bool

- name: Ensure using DetectionLab inputs.conf
  win_copy:
    src: "{{ detectionlab_gitroot }}\\vagrant\\resources\\splunk_forwarder\\wef_inputs.conf"
    dest: 'C:\Program Files\SplunkUniversalForwarder\etc\apps\Splunk_TA_windows\local\inputs.conf'
    remote_src: true
