---
# https://github.com/clong/DetectionLab/blob/master/Vagrant/scripts/install-wefsubscriptions.ps1

- name: Ensure Palantir windows-event-forwarding are present in system
  win_copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    remote_src: true
  with_items:
    - { s: 'c:\Program Files\windows-event-forwarding\windows-event-channels\CustomEventChannels.dll',
        d: 'c:\windows\system32\CustomEventChannels.dll'
      }
    - { s: 'c:\Program Files\windows-event-forwarding\windows-event-channels\CustomEventChannels.man',
        d: 'c:\windows\system32\CustomEventChannels.man'
      }

- name: Check if EventLog channel exists
  win_reg_stat:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WINEVT\Channels\WEC-Powershell'
  register: cec

- block:
    - name: Create CustomEventChannels Event Log
      win_command: >
        wevtutil im "c:\windows\system32\CustomEventChannels.man"
    - name: Resizing Channels to 4GB
      win_command: >
        wevtutil sl {{ item }} /ms:4294967296
      with_items:
        - WEC-Powershell
        - WEC-WMI
        - WEC-EMET
        - WEC-Authentication
        - WEC-Services
        - WEC-Process-Execution
        - WEC-Code-Integrity
  when: not cec.exists

- name: Ensure WEC service is started
  win_service:
    name: wecsvc
    state: started
    start_mode: auto

- name: Check if Palantir wef-subscriptions are marked loaded
  win_stat:
    path: 'c:\Program Files\windows-event-forwarding\.wef_loaded'
  register: wef_loaded

- block:
    - name: Load Palantir wef-subscriptions
      win_command: >
        wecutil cs {{ item }}.xml
      args:
        chdir: c:\Program Files\windows-event-forwarding\wef-subscriptions
      with_items: "{{ wef_palantir_subscriptions }}"
      ignore_errors: true
      register: lwef

    # debug
    - name: Get Palantir wef-subscriptions
      win_command: >
        wecutil gs {{ item }}
      args:
        chdir: c:\Program Files\windows-event-forwarding\wef-subscriptions
      with_items: "{{ wef_palantir_subscriptions }}"
      changed_when: false

    - name: Retry Palantir wef-subscriptions
      win_command: >
        wecutil rs {{ item }}
      args:
        chdir: c:\Program Files\windows-event-forwarding\wef-subscriptions
      with_items: "{{ wef_palantir_subscriptions }}"
      ignore_errors: true
      when: lwef is failed

    - name: Enable Palantir wef-subscriptions
      win_command: >
        wecutil ss {{ item }} /e:true
      args:
        chdir: c:\Program Files\windows-event-forwarding\wef-subscriptions
      ignore_errors: true
      with_items: "{{ wef_palantir_subscriptions }}"

    - name: Enabling WecUtil Quick Config...
      win_command: >
        wecutil qc /q:true

    - name: Add marker for Palantir wef-subscriptions
      win_file:
        path: 'c:\Program Files\windows-event-forwarding\.wef_loaded'
        state: touch
  when: not wef_loaded.stat.exists
