---

- name: restart splunk forwarder
  win_service:
    name: splunkforwarder
    state: restarted

- name: Disable IPv6 on all network adapters
  win_shell: Get-NetAdapterBinding -ComponentID ms_tcpip6 | ForEach-Object {Disable-NetAdapterBinding -Name $_.Name -ComponentID ms_tcpip6}

- name: Set Task Manager prefs
  win_command: "reg import \"{{ detectionlab_gitroot }}\\vagrant\\resources\\windows\\TaskManager.reg\""

- name: Windows reboot
  win_reboot:
  when: detectionlab_win_reboot is defined and detectionlab_win_reboot|bool

- name: Run gpupdate
  win_command: gpupdate /force
